/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8112c183-0bc2-44d5-8d63-f5c45757718a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rRwpqKnOf",
    "aws_user_pools_web_client_id": "62vc88opp0ht7tnpavsfo47kf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://gpg4mb3dnjcync2b2vuz2vt6li.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iddxm65e3ncbvpazr3mgduk7hi",
    "aws_user_files_s3_bucket": "csv-transition",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
